import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul>
          <li>
            <Link href="/">Головна</Link>
          </li>
          <li>
            <Link href="/about">Про нас</Link>
          </li>
          <li>
            <Link href="/products">Продукти компанії</Link>
          </li>
          <li>
            <Link href="/services">Послуги</Link>
          </li>
          <li>
            <Link href="/vacancies">Робота</Link>
          </li>
          <li>
            <Link href="/contacts">Контакти</Link>
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
