import './globals.css';
import Link from 'next/link';
import { IBMPlexSans, nunito } from './fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${IBMPlexSans.variable} ${nunito.variable} font-heading bg-dark-gradient text-primary min-h-screen`}
      >
        <ul className="flex flex-wrap gap-4 font-bold text-4xl justify-center p-4 hover:[&_a]:text-sky-600 [&_a]:transition-colors [&_a]:duration-300">
          <li>
            <Link href="/">Головна</Link>
          </li>
          <li>
            <Link href="/about">Про нас</Link>
          </li>
          <li>
            <Link href="/products">Продукти компанії</Link>
          </li>
          <li>
            <Link href="/services">Послуги</Link>
          </li>
          <li>
            <Link href="/vacancies">Робота</Link>
          </li>
          <li>
            <Link href="/contacts">Контакти</Link>
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
